feat: forgot and reset password
Agility-Creative-Solutions/ez2live-app pull request #15
Opened 2023-08-03 02:40 UTC by femacedogomes

2023-08-04 14:45 UTC, pedrohbl03 requested changes
Resolve all requests appointed in PR from login page here to.

2023-08-04 14:45 UTC, pedrohbl03 commented on src/app/forgotPassword/FormComponent.tsx
> +        await Auth.forgotPassword({
Show comments on [this PR](https://github.com/Agility-Creative-Solutions/ez2live-app/pull/14)

2023-08-08 15:21 UTC, pedrohbl03 commented on src/app/resetPassword/[token]/page.tsx
> +  const handleFormSubmit = async (values : any) => {
```suggestion
  const handleFormSubmit = async (values : Partial<IResetPassword>) => {
```

2023-08-08 15:52 UTC, pedrohbl03 commented on src/app/forgotPassword/FormComponent.tsx
> +    .then(()=> {
```suggestion
    .then((response)=> {
```

2023-08-14 15:12 UTC, pedrohbl03 commented on src/app/forgot-password/page.tsx
> +          Recuperar <br/>
What is broke line here?
```suggestion
          Recuperar
```

2023-08-14 15:16 UTC, pedrohbl03 requested changes
@femacedogomes Resolve the comment where u set a "Broken line" pls.

2023-08-15 19:43 UTC, femacedogomes commented on src/app/forgot-password/page.tsx
> +          Recuperar <br/>
its only for design

2023-08-16 15:05 UTC, pedrohbl03 approved these changes
gj

2023-08-16 15:05 UTC, merged