feat: subscription page on account profile
Agility-Creative-Solutions/ez2live-app pull request #161
Opened 2024-04-29 18:14 UTC by femacedogomes

2024-05-06 18:11 UTC, renanpontez commented on src/app/app/(application)/minha-conta/account.tsx
> +import { Session } from "next-auth";
isso nao deveria ser importado como type já que ta sendo usado como tipagem na linha 10?

2024-05-06 18:12 UTC, renanpontez commented on src/app/app/(application)/minha-conta/page.tsx
> +  const [pageId, setPageId] = useState<"account" | "security" | "signature">(
subscription

2024-05-06 18:12 UTC, femacedogomes commented
Para acessar as aletrações é preciso estar logado e entrar na página /app/minha-conta e escolher a aba de assinatura

2024-05-06 18:12 UTC, renanpontez commented on src/app/app/(application)/minha-conta/page.tsx
> +  }, [pageId]);
Esse trecho de if/else aqui tá bem feio. 
Alo @pedrohbl03 sugere um refactor aqui

2024-05-06 18:14 UTC, renanpontez commented on src/app/app/(application)/minha-conta/signature.tsx
> +import { Session } from "next-auth";
mesma coisa aqui sobre o type

2024-05-06 18:15 UTC, renanpontez commented on src/app/app/(application)/minha-conta/signature.tsx
> +  if (session === null) return <div>sessão indisponível</div>;
Se nao tiver sessao vai retornar uma só uma div?

E quando isso vai acontecer? Tipo, existe algum cenário onde um usuário vai ser possível de ver essa tela e nao ter session? 

Não seria uma falha do app deixar isso acontecer?

2024-05-06 18:16 UTC, renanpontez commented on src/app/app/(application)/minha-conta/signature.tsx
> +  if (session === null) return <div>sessão indisponível</div>;
Só sei que retornar `<div>sessão indisponível</div>` não é algo previsto pela gente. 
Se não tem sessão, nunca nem deveria entrar aqui, teria que morrer antes pro `/conta/entrar`.

Qlqr coisa pede help pro Pedro

2024-05-06 18:16 UTC, renanpontez commented on src/app/app/(application)/minha-conta/signature.tsx
> +  const [openCancelSignatureModal, SetOpenCancelSignatureModal] =
`SetOpenCancelSignatureModal` +1 proteinbar

2024-05-06 18:18 UTC, renanpontez commented on src/app/app/(application)/minha-conta/signature.tsx
> +  const [openCancelSignatureModal, SetOpenCancelSignatureModal] =
Inclusive pra melhorar: `setIsCancelSubscriptionOpened`

Uma dica que já enviei e vou mandar de novo (salva no bookmark): https://google.github.io/styleguide/jsguide.html

2024-05-06 18:35 UTC, renanpontez commented on src/components/atoms/Button/Button.tsx
> +    twFocusClass(false);
A gente pode refatorar isso com a lib `classNames`: https://github.com/JedWatson/classnames

2024-05-06 18:37 UTC, renanpontez requested changes
Deixei alguns comments marotos. Qlqr coisa liga nois.
Por favor, antes de resolver o comentário, responde eles só com "corrigido" ou "nao foi feito: [motivo]" pra eu ter noção pra fazer a re-review dps :D

2024-05-09 00:25 UTC, renanpontez commented on src/app/app/(application)/minha-conta/security.tsx
> +  const [handleModal, setHandleModal] = useState(false);
```suggestion
  const [isDeleteAccountOpened, setIsDeleteAccountOpened] = useState(false);
```

2024-05-09 00:26 UTC, renanpontez commented on src/app/app/(application)/minha-conta/security.tsx
> +  const [disableButtonSendEmail, setDisableButtonSendEmail] = useState(false);
```suggestion
  const [isSendEmailDisabled, setIsSendEmailDisabled] = useState(false);
```

2024-05-09 00:27 UTC, renanpontez commented on src/app/app/(application)/minha-conta/security.tsx
> +        show={handleModal}
```suggestion
        show={isDeleteAccountOpened}
```

2024-05-09 00:28 UTC, renanpontez commented on src/app/app/(application)/minha-conta/security.tsx
> +        }}
Acredito que esse async aqui é desnecessário, já tem na funçao

2024-05-09 00:28 UTC, renanpontez commented on src/app/app/(application)/minha-conta/security.tsx
> +  const [emailSendButton, setEmailSendButton] = useState("Trocar senha");
```suggestion
  const [sendEmailButtonText, setSendEmailButtonText] = useState("Trocar senha");
```

2024-05-09 00:29 UTC, renanpontez commented on src/app/app/(application)/minha-conta/security.tsx
> +                  label="senha"
Não deveria ser "Senha" ? Validar outros pontos do codigo tbm nao sei se tem

2024-05-09 00:29 UTC, renanpontez commented on src/app/app/(application)/minha-conta/security.tsx
> +                    label="Password"
Aqui é Password mesmo ou Senha?

2024-05-09 00:30 UTC, renanpontez commented on src/app/app/(application)/minha-conta/subscription.tsx
> +    // END-POINT CANCEL SUBSCRIPTION
```suggestion
    // TODO: CONECTAR ENDPOINT PARA CANCELAR SUBSCRIPTION
```

2024-05-09 00:31 UTC, renanpontez commented on src/app/app/(application)/minha-conta/subscription.tsx
> +  ) : (
Não deveria ser o contrário? Se tem assinatura, mostra os dados dela, se nao tem, mostra o CTA.

Também sugiro trocar por: `user.subscription` ou `userSubscription`

2024-05-09 00:31 UTC, renanpontez commented on src/app/app/(application)/minha-conta/subscription.tsx
> +  ) : (
Tbm traduzir em todos os outros lugares que tem signatura pleaseeee

2024-05-09 00:32 UTC, renanpontez requested changes
Alguns ajustes marotos

2024-05-10 00:28 UTC, pedrohbl03 commented on src/app/app/(application)/minha-conta/page.tsx
> +  }, [pageId]);
const TabComponent = useMemo({
  ACCOUNT: <Account session={session} />;
  SECURITY: <Security session={session} />;
  SIGNATURE: <Signature session={session} />;
}, [pageId]);

Para fazer a chamada do componente: 
`{TabComponent[pageId.toUppercase()]}`

2024-05-10 00:37 UTC, pedrohbl03 commented on src/app/app/(application)/minha-conta/page.tsx
> +  }, [pageId]);
@femacedogomes

2024-05-10 18:34 UTC, renanpontez commented on src/app/app/(application)/minha-conta/page.tsx
> +  }, [pageId]);
coisa linda

2024-05-12 16:41 UTC, pedrohbl03 commented on src/app/app/(application)/minha-conta/security.tsx
> +                    label="Password"
@femacedogomes

2024-05-12 16:41 UTC, pedrohbl03 commented on src/app/app/(application)/minha-conta/security.tsx
> +                    label="Password"
Linha 120 e 128

2024-05-12 22:41 UTC, renanpontez commented on src/app/app/(application)/minha-conta/security.tsx
> +                    label="Password"
```suggestion
                    label="Senha"
```

2024-05-12 22:41 UTC, renanpontez approved these changes

2024-05-12 22:43 UTC, renanpontez approved these changes
Mergear DEPOIS da feat-payment-page estar na dev. Esta branch entao sera trocada automaticamente pra `dev`. Resolve os conflitos e entao merge liberado! 👍

2024-05-13 02:13 UTC, merged