Fix search icon/ Coupon Create andupdateComponent/ Uppercase corrections / change "deletar cupom" to "excluir cupom"
Agility-Creative-Solutions/ez2live-app pull request #169
Opened 2024-05-17 18:24 UTC by femacedogomes

2024-05-18 16:21 UTC, renanpontez commented on src/app/(landing-page)/components/SectionPromo2.tsx
>  const CONTENT_BY_CATEGORY = {
Pera ai, pra que serve esse `CONTENT_BY_CATEGORY` se as categorias de comidas estao cadastradas no banco de dados?

![image](https://github.com/Agility-Creative-Solutions/ez2live-app/assets/8492847/170b8d97-a2c0-4f8b-ba37-cd72737d0cc5)

E outra: objeto com chave contendo acento, caractere especial e letras maiusculas e minusculas?
Nao ta com cara de gambiarra nao isso?

2024-05-18 16:23 UTC, renanpontez commented on src/app/(landing-page)/components/SectionPromo2.tsx
>  const CONTENT_BY_CATEGORY = {
No front deveria no maximo ter um "de -> para" apontando pros ids.. nomes e descricoes deveriam ser gerenciadas somente no banco de dados pq senao a cada categoria nova uma ruma de alteracoes no front sao necessarias, quando o cenario ideal e nao ter nenhum (ai precisaria de API pra manter as categorias) por isso a necessidade do "de-para".

qlqr coisa chama o @pedrohbl03 pra tirar essa duvida de organizacao ai

2024-05-18 16:26 UTC, renanpontez commented on src/app/(landing-page)/components/SectionPromo2.tsx
>  const CONTENT_BY_CATEGORY = {
Mas isso aqui nao rola ter no nosso codigo:

```
const test = {
  Promoção: {...}
  ÓéçÂõáÎC: {...}
  ...
}
```

talvez algo como:
```
const categories = {
  6583288ca8101b0027ecd823: {
    title: '',
    description: '',
    ...
  },
  ...
}
 ```
 
 obs: nao ja tem isso no codigo nao? 🤔

2024-05-18 16:26 UTC, renanpontez commented on src/app/app/(authentication)/conta/(withHeader)/(public)/cadastrar/parceiro/FormComponent.tsx
> +                  selecione uma categoria
```suggestion
                  Selecione uma categoria
```

2024-05-18 16:28 UTC, renanpontez commented on src/app/app/(authentication)/conta/(withHeader)/(public)/entrar/page.tsx
> +              registrar
- ⁠”registrar com e-mail/senha” -> “Registrar”

era sobre o maiusculo só... dps de acento começa outra oração viu 🤣

2024-05-18 16:28 UTC, renanpontez commented on src/app/app/(authentication)/conta/(withHeader)/(public)/entrar/page.tsx
> +              registrar
```suggestion
              Registrar com email/senha
```

2024-05-18 16:29 UTC, renanpontez commented on src/components/atoms/AvatarDropdown/index.tsx
> -                  </p>
E ai, nao vamos ter mais nenhuma UX do "desconetando"?
A task nao seria pra arrumar o bug visual que tava causando?

2024-05-18 16:29 UTC, renanpontez commented on src/components/mols/CreateAndUpdateCoupon/index.tsx
> +              excluir cupom
```suggestion
              Excluir cupom
```

2024-05-18 16:31 UTC, renanpontez commented on src/components/atoms/AvatarDropdown/index.tsx
> -                  </p>
Opa vi aqui que ta rodando a bolinha de loading la. Ta top! Desconsiderar hahah

2024-05-18 16:33 UTC, renanpontez requested changes
pequenos comentarios

2024-05-18 23:49 UTC, femacedogomes commented on src/app/app/(authentication)/conta/(withHeader)/(public)/entrar/page.tsx
> +              registrar
ta massa kkkkkk.
corrigido

2024-05-18 23:49 UTC, femacedogomes commented on src/app/app/(authentication)/conta/(withHeader)/(public)/cadastrar/parceiro/FormComponent.tsx
> +                  selecione uma categoria
Corrigido

2024-05-18 23:50 UTC, femacedogomes commented on src/app/app/(authentication)/conta/(withHeader)/(public)/entrar/page.tsx
> +              registrar
feito..

2024-05-18 23:51 UTC, femacedogomes commented on src/components/mols/CreateAndUpdateCoupon/index.tsx
> +              excluir cupom
Corrigido

2024-05-18 23:52 UTC, femacedogomes commented on src/components/mols/CreateAndUpdateCoupon/index.tsx
> +              excluir cupom
Corrigido

2024-05-19 00:53 UTC, femacedogomes commented on src/app/(landing-page)/components/SectionPromo2.tsx
>  const CONTENT_BY_CATEGORY = {
Na verdade essa section nem ta sendo utilizada. Foi daquela primeira versão da landingPage. Vou remover as seções que não foram inutilizadas.

2024-05-20 02:05 UTC, renanpontez approved these changes

2024-05-20 02:32 UTC, merged