WIP: Get user subscriptionInfo in My-Account / CreditCard error handler.
Agility-Creative-Solutions/ez2live-app pull request #172
Opened 2024-05-20 00:30 UTC by femacedogomes

2024-05-20 01:58 UTC, renanpontez commented on src/app/app/(application)/minha-conta/page.tsx
> +import { IGetSubscriptionResponse } from "@/types/auth/response";
types nao precisam ser importados como

`import type { } from "..."`

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html

2024-05-20 01:59 UTC, renanpontez commented on src/app/app/(application)/minha-conta/page.tsx
>    const [pageId, setPageId] = useState<"ACCOUNT" | "SECURITY" | "SIGNATURE">(
signature = subscription

ja tinha comentado isso no PR anterior ao merge Oo

2024-05-20 01:59 UTC, renanpontez commented on src/app/app/(application)/minha-conta/page.tsx
> +          console.log("Subscription Info:", subscriptionInfo); // Adicione este console.log
👀

2024-05-20 01:59 UTC, renanpontez commented on src/app/app/(application)/minha-conta/page.tsx
> +      ),
+1 protein bar

signature = subscription

2024-05-20 01:59 UTC, renanpontez commented on src/app/app/(application)/minha-conta/page.tsx
> +        <Signature session={session} subscriptionInfo={subscriptionInfo} />
SubscriptionTab pra ficar mais claro o que é o componente

2024-05-20 02:00 UTC, renanpontez commented on src/types/auth/response/index.ts
> +  status: "paid" | "unpaid"; // ou qualquer outro status possível
isso aqui ta fazendo sentido nao: // ou qualquer outro status possível

vai ser um dos dois aqui ou o tipagem ta errada: "paid" | "unpaid"

2024-05-20 02:01 UTC, renanpontez commented on src/types/auth/response/index.ts
> +  subitems: unknown[]; // ou outro tipo específico
powered by chatgpt?

2024-05-20 02:01 UTC, renanpontez commented on src/types/auth/response/index.ts
> +  customVariables: unknown[]; // ou outro tipo específico
powered by chatgpt?

2024-05-20 02:01 UTC, renanpontez commented on src/types/auth/response/index.ts
> +  ignoreDueEmail: null | unknown; // ou outro tipo específico
powered by chatgpt?

2024-05-20 02:01 UTC, renanpontez commented on src/types/auth/response/index.ts
> +  features: Record<string, unknown>; // ou outro tipo específico
powered by chatgpt?

2024-05-20 02:01 UTC, renanpontez commented on src/types/auth/response/index.ts
> +export interface IGetSubscriptionResponse {
A gente vai precisar de tudo isso?

2024-05-20 02:01 UTC, renanpontez commented on src/types/auth/response/index.ts
> +  inTrial: null | unknown; // ou outro tipo específico
powered by chatgpt?

2024-05-20 02:02 UTC, renanpontez requested changes
powered by chatgpt?

2024-05-20 02:05 UTC, femacedogomes commented on src/types/auth/response/index.ts
> +  subitems: unknown[]; // ou outro tipo específico
T.T

2024-05-20 02:05 UTC, femacedogomes commented on src/types/auth/response/index.ts
> +  features: Record<string, unknown>; // ou outro tipo específico
T.t

2024-05-20 02:13 UTC, femacedogomes commented on src/types/auth/response/index.ts
> +  ignoreDueEmail: null | unknown; // ou outro tipo específico
T.t

2024-05-20 02:13 UTC, femacedogomes commented on src/types/auth/response/index.ts
> +  customVariables: unknown[]; // ou outro tipo específico
T.t

2024-05-20 02:13 UTC, femacedogomes commented on src/types/auth/response/index.ts
> +  status: "paid" | "unpaid"; // ou qualquer outro status possível
isso realmente foi um erraço meu

2024-05-20 02:17 UTC, femacedogomes commented on src/app/app/(application)/minha-conta/page.tsx
> +        <Signature session={session} subscriptionInfo={subscriptionInfo} />
done

2024-05-20 02:17 UTC, femacedogomes commented on src/app/app/(application)/minha-conta/page.tsx
> +      ),
done

2024-05-20 02:17 UTC, femacedogomes commented on src/app/app/(application)/minha-conta/page.tsx
> +          console.log("Subscription Info:", subscriptionInfo); // Adicione este console.log
KKKKKKKKKKKKKKKKrying

2024-05-20 02:20 UTC, femacedogomes commented on src/app/app/(application)/minha-conta/page.tsx
> +          console.log("Subscription Info:", subscriptionInfo); // Adicione este console.log
Foi um vacilo meu que tava criandoo componente antes do pai dele atualizar os valores da props que passava pra ele e tentei descobrir usando o console.log

2024-05-20 02:20 UTC, femacedogomes commented on src/app/app/(application)/minha-conta/page.tsx
> +          console.log("Subscription Info:", subscriptionInfo); // Adicione este console.log
corrigido

2024-05-20 02:20 UTC, femacedogomes commented on src/app/app/(application)/minha-conta/page.tsx
>    const [pageId, setPageId] = useState<"ACCOUNT" | "SECURITY" | "SIGNATURE">(
resolvido

2024-05-20 02:23 UTC, femacedogomes commented on src/app/app/(application)/minha-conta/page.tsx
> +import { IGetSubscriptionResponse } from "@/types/auth/response";
![image](https://github.com/Agility-Creative-Solutions/ez2live-app/assets/104227174/d1fda036-b584-4bd4-8ab3-3b72c9628099)

2024-05-20 02:24 UTC, femacedogomes commented on src/app/app/(application)/minha-conta/page.tsx
> +import { IGetSubscriptionResponse } from "@/types/auth/response";
pior que quando eu tento, o ts apita esse erro

2024-05-22 17:29 UTC, renanpontez approved these changes

2024-05-22 17:37 UTC, merged