WIP: Feat improv subscription page
Agility-Creative-Solutions/ez2live-app pull request #174
Opened 2024-05-21 02:13 UTC by femacedogomes

2024-05-21 14:33 UTC, femacedogomes commented
Realizar logIn e ir pra página /minha-conta na aba de subscription.
https://deploy-preview-174--ez2live.netlify.app/app/minha-conta

2024-06-03 01:18 UTC, pedrohbl03 requested changes

2024-06-03 01:18 UTC, pedrohbl03 commented on src/app/app/(application)/minha-conta/page.tsx
> +  const getSubsCriptionInfo = async () => {
```suggestion
  const getSubscriptionInfo = async () => {
```

2024-06-03 01:18 UTC, pedrohbl03 commented on src/app/app/(application)/minha-conta/page.tsx
> +          setPaymentMethodInfo={setPaymentMethodInfo}
```suggestion
          setPaymentMethodInfo={handlePaymentMethodInfo}
```

2024-06-03 01:18 UTC, pedrohbl03 commented on src/app/app/(application)/minha-conta/page.tsx
> +          setPaymentMethodInfo={setPaymentMethodInfo}
const handlePaymentMethodInfo = (paymentMethod: string) => {
   setPaymentMethodInfo(paymentMethod)
}

2024-06-03 02:32 UTC, femacedogomes commented on src/app/app/(application)/minha-conta/page.tsx
> +  const getSubsCriptionInfo = async () => {
done

2024-06-03 02:47 UTC, merged