Profile page [TAS-54]
Agility-Creative-Solutions/ez2live-app pull request #23
Opened 2023-08-23 02:46 UTC by femacedogomes

2023-08-23 02:48 UTC, femacedogomes commented
Neste Pr também foi removido a classe de Dark Theme dos components

2023-08-24 21:21 UTC, pedrohbl03 commented on src/app/(accounts)/layout.tsx
> +const pages: {
u can create a navigation.constants and place this object; 
Because this makes maintenance easy everywhere

2023-08-24 21:21 UTC, pedrohbl03 requested changes
Change the comment in accounts/layout plz.

2023-09-02 19:24 UTC, femacedogomes commented
just waiting for new end point delete user to really finish. But we can also made a correction in other components.

2023-09-10 05:03 UTC, renanpontez approved these changes

2023-09-12 00:34 UTC, merged