Feat/create coupon component
Agility-Creative-Solutions/ez2live-app pull request #37
Opened 2023-09-22 16:36 UTC by femacedogomes

To see the Create Coupon Button, u need to be logged in authorized supplier account.
Use this login ---- > username: teste4@gmail.com , password: 123123qwe

u can see it in /dashboard/supplier/profile

2023-09-22 16:42 UTC, femacedogomes commented
A put console.log(values) on form to resolve de build problem that values as never been used.
No protein bar to u , Renan

2023-09-23 12:56 UTC, renanpontez commented on src/app/teste/page.tsx
> +export default TestePage
new line

2023-09-23 12:57 UTC, renanpontez commented on src/components/atoms/CreateCoupon/index.tsx
> +    console.log(values)
+1 protein bar

2023-09-28 23:17 UTC, pedrohbl03 commented
Layout that's good!

2023-09-28 23:49 UTC, pedrohbl03 requested changes
Has a minimal changes, but in [file](https://github.com/Agility-Creative-Solutions/ez2live-app/pull/37/files/758ddf8abb6580b8b9617561cc31c6692c295587#diff-e5788a07dbe1dc1237c26765fa93d25811a57b653c0dc237388ae369bccf813b) at line 159, has a ternary verification so hard. I don't think anything to resolve this. @renanpontez can u help-me with this? 

I believe object map resolve this problem, but it's not clear now. Let's talk about pls?

2023-09-28 23:49 UTC, pedrohbl03 commented on src/components/atoms/ButtonClose/ButtonClose.tsx
> -  IconclassName = "w-5 h-5",
iconClassName

2023-09-28 23:49 UTC, pedrohbl03 commented on src/components/atoms/FormItem/index.tsx
>  export interface formItemProps {
IFormItemProps

2023-09-28 23:49 UTC, pedrohbl03 commented on src/components/mols/CreateCoupon/index.tsx
> +    coupon_limit: Yup.string().required(
string? this is number

2023-09-28 23:49 UTC, pedrohbl03 commented on src/components/mols/CreateCoupon/index.tsx
> +    user_limit: Yup.string().required("Limite de cupons por usuário."),
number too

2023-09-28 23:49 UTC, pedrohbl03 commented on src/components/mols/CreateCoupon/index.tsx
> +                  value={
Add multiples ternary verification has a bad practice because the code so difficult to read. Has a other way to make this?

2023-09-28 23:49 UTC, pedrohbl03 commented on src/components/mols/CreateCoupon/index.tsx
> +                  value={
We can talk about this tomorrow

2023-10-03 19:33 UTC, renanpontez approved these changes
LGTM NICE!

2023-10-03 19:35 UTC, pedrohbl03 requested changes

2023-10-03 19:35 UTC, pedrohbl03 commented on src/components/atoms/toggleButton/index.tsx
toggleButton? this folder need start with first letter upper; ToggleButton

2023-10-03 19:35 UTC, pedrohbl03 commented on src/app/page.tsx
> +        "supplierInfo.supplierCategory": supplierCategoriesFilter,
```suggestion
        supplierInfo.supplierCategory: supplierCategoriesFilter,
```

2023-10-03 19:41 UTC, pedrohbl03 approved these changes

2023-10-03 22:47 UTC, merged