Register and login api [TAS-40]
Agility-Creative-Solutions/ez2live-app pull request #4
Opened 2023-07-10 18:11 UTC by femacedogomes

2023-07-11 21:09 UTC, renanpontez commented on .gitignore
> +*.env
Change this to .env*

2023-07-11 21:09 UTC, renanpontez commented on .gitignore
> +*.env
Don't forget to add a new line at the end of ALL the files

2023-07-11 21:09 UTC, renanpontez commented on src/config/config.ts
> +}
Don't forget to add a new line at the end of ALL the files

2023-07-11 21:09 UTC, renanpontez commented on .env
> +MONGODB_URL=mongodb+srv://dbuser:0KEOy46rIJJ4Pq3D@dev-cluster.mzkybvz.mongodb.net/?retryWrites=true&w=majority
Please remove this. MongoDB URL is not need in the front-end. Also the password is being leaked.

2023-07-11 21:14 UTC, renanpontez commented on src/types/auth/index.ts
> +  email:string;
add space

2023-07-11 21:15 UTC, renanpontez commented on src/types/auth/index.ts
> +export interface LogInType {
Rename this to: `ILogIn ` to follow the best practice

2023-07-11 21:15 UTC, renanpontez commented on src/types/auth/index.ts
> +export interface RegisterAccountType {
Rename this to: `IRegisterAccount` to follow the best practice

2023-07-11 21:16 UTC, renanpontez commented on src/service/auth/service.ts
> +}
Let's extract the login and register functions to outside this UserService object which is not needed.

We need to export only the functions directly.

2023-07-11 21:16 UTC, renanpontez requested changes
Left some comments. Also @pedrohbl03 will take a look

2023-07-17 16:51 UTC, pedrohbl03 approved these changes

2023-07-17 17:34 UTC, merged