feat/my-coupons-page [TAS-53]
Agility-Creative-Solutions/ez2live-app pull request #40
Opened 2023-10-03 03:22 UTC by femacedogomes

still not conected with api

2023-10-03 19:18 UTC, pedrohbl03 requested changes

2023-10-03 19:18 UTC, pedrohbl03 commented on src/app/my-coupons/page.tsx
> +const ArrayCoupons = [
This is a fake data? 

We are need this now?

2023-10-03 19:18 UTC, pedrohbl03 commented on src/components/atoms/SupplierCoupons/index.tsx
> +  expirateTime: number | string;
Date has a type too.

2023-10-03 19:18 UTC, pedrohbl03 commented on src/components/atoms/SupplierCoupons/index.tsx
> +            src={status == "expired" ? CouponRed : CouponPrimary}
u can compare  type and value, pls use ===
```suggestion
            src={status === "expired" ? CouponRed : CouponPrimary}
```

2023-10-03 19:18 UTC, pedrohbl03 commented on src/components/atoms/SupplierCoupons/index.tsx
> +          status == "used" ? "text-primary-main" : "text-white"
===
```suggestion
          status === "used" ? "text-primary-main" : "text-white"
```

2023-10-03 19:18 UTC, pedrohbl03 commented on src/components/atoms/SupplierCoupons/index.tsx
> +          {status == "active" ? (
```suggestion
          {status === "active" ? (
```

2023-10-03 19:18 UTC, pedrohbl03 commented on src/components/atoms/SupplierCoupons/index.tsx
> +            {status == "expired" && (
```suggestion
            {status === "expired" && (
```

2023-10-03 19:18 UTC, pedrohbl03 commented on src/components/atoms/SupplierCoupons/index.tsx
> +            {status == "used" && (
```suggestion
            {status === "used" && (
```

2023-10-03 19:22 UTC, pedrohbl03 commented on src/components/atoms/SupplierCoupons/index.tsx
> +            {status == "used" && (
U can use a ObjectMap to make this. 

const STATUS_COMPONENTS = {
used: <div>...</div>,
expired: <div>...</div>,
...
}


And remove all if ternarys for it: `{STATUS_COMPONENTS[status] && STATUS_COMPONENTS[status]}`

2023-10-06 16:57 UTC, pedrohbl03 requested changes

2023-10-06 16:57 UTC, pedrohbl03 commented on src/app/my-coupons/page.tsx
> +interface filterOptions {
IFilterOptions

All interfaces starts with a Upper "i"

2023-10-06 16:57 UTC, pedrohbl03 commented on src/app/my-coupons/page.tsx
> +          className={`${
Refactor for a ObjectMap.

const COUPONS_FILTER={
user: "text-black",
....
}

2023-10-06 16:57 UTC, pedrohbl03 commented on src/app/my-coupons/page.tsx
> +                option.id == "used"
object map too

2023-10-06 16:57 UTC, pedrohbl03 commented on src/components/atoms/CurrencyDropdown/index.tsx
> +                ${open ? "" : "text-opacity-100"}
!open && "text-opacity-100"

2023-10-06 16:57 UTC, pedrohbl03 commented on src/components/atoms/SupplierCoupons/index.tsx
> +        status === "used"
Objectmap too

2023-10-06 16:57 UTC, pedrohbl03 commented on src/components/orgs/CouponListPage/index.tsx
> +                expirateTime={"5"}
why this is not a number?

2023-10-06 16:57 UTC, pedrohbl03 commented on src/components/atoms/SupplierCoupons/index.tsx
> +  expirateTime: string;
why this is not a number?

2023-10-06 17:11 UTC, renanpontez commented on src/components/atoms/SupplierCoupons/index.tsx
> +          : "bg-primary-main"
This is wrong. We should NOT use multiples ternaries

2023-10-06 17:13 UTC, renanpontez commented on src/components/atoms/SupplierCoupons/index.tsx
> +          : "bg-primary-main"
Try using a different approach using an object or a function to find the background-color according to the status.

Option 1:

const BG_COLORS_BY_STATUS = {
  used: 'bg-secondary-main',
  expired 'bg-generic-alertRed',
  ....
}



Option 2: 

const getBgColorByStatus = (status) => { ... }

2023-10-06 17:14 UTC, renanpontez commented on src/components/atoms/SupplierCoupons/index.tsx
> +          : "bg-primary-main"
Remember: if you need to do `if, else if, else if, else if....`, the ternary is not the best option. It will if it's only: `if, else`

2023-10-06 17:28 UTC, renanpontez commented on src/components/atoms/SupplierCoupons/index.tsx
> +    ),
Ideally this could be only 1 component changing only its props based on the status prop

2023-10-10 17:54 UTC, renanpontez approved these changes

2023-10-11 00:28 UTC, merged