WIP: Feat/edit and remove coupon
Agility-Creative-Solutions/ez2live-app pull request #47
Opened 2023-10-13 21:07 UTC by femacedogomes

2023-10-15 16:38 UTC, femacedogomes commented
To test the update and remove  coupon component u need to be logged in supplier activated account and create your own coupon.
u can use  
username: sup_felipe@email.com
password: qweqwe123
page: https://deploy-preview-47--ez2live.netlify.app/dashboard/supplier/profile

2023-10-15 21:56 UTC, pedrohbl03 commented on src/components/mols/CouponActived/index.tsx
> +import useDateFormater from "@/utils/DateFormater";
```suggestion
import getDeteFormater from "@/utils/DateFormater";
```

2023-10-15 22:02 UTC, pedrohbl03 requested changes

2023-10-15 22:02 UTC, pedrohbl03 commented on src/utils/DateFormater.ts
> +const DateFormater = (date?: string) => {
```suggestion
export const getDateFormater= (date?: string) => {
```

2023-10-15 22:02 UTC, pedrohbl03 commented on src/utils/DateFormater.ts
> +const DateFormater = (date?: string) => {
Change the file name to "getDateFormater" too

2023-10-15 22:02 UTC, pedrohbl03 commented on src/utils/DateFormater.ts
> +export default DateFormater;
```suggestion

```
remove this

2023-10-15 23:40 UTC, pedrohbl03 approved these changes

2023-10-21 19:21 UTC, pedrohbl03 commented
@renanpontez @femacedogomes  closed

2023-10-21 19:21 UTC, merged