WEIP: feat: New users login Flow [TAS-94]
Agility-Creative-Solutions/ez2live-app pull request #55
Opened 2023-11-08 00:12 UTC by femacedogomes

2023-11-10 21:23 UTC, renanpontez commented on src/app/(authentication)/auth/(withHeader)/(public)/register/user/FormComponent.tsx
> +            callbackUrl: callbackUrl ? callbackUrl : "/",
This is the same as: `callbackUrl: callbackUrl ?? "/",`

2023-11-10 21:23 UTC, renanpontez commented on src/app/(authentication)/auth/(withHeader)/(public)/register/user/FormComponent.tsx
>                console.log(resp);
+1 protein bar

2023-11-10 21:26 UTC, renanpontez commented on src/components/orgs/Coupon/Container.tsx
> +        callbackUrl: `/supplier-dashboard/${supplierId}/?coupon=${CouponId}`,
```suggestion
        callbackUrl: `/supplier-dashboard/${supplierId}/?coupon=${couponId}`,
```

Please watch out case

2023-11-10 21:27 UTC, renanpontez approved these changes
looks good, just small non-blocking comments.

2023-11-12 23:33 UTC, pedrohbl03 requested changes

2023-11-13 15:05 UTC, femacedogomes commented on src/app/(authentication)/auth/(withHeader)/(public)/login/FormComponent.tsx
> +        if (error?.code === "R01") {
thats the name of the error sended by back-end

2023-11-13 19:54 UTC, merged